language: node_js
node_js:
- '6'
- '7'
- '8'
deploy:
  provider: npm
  email: wolf@okwolf.com
  api_key:
    secure: R0ehkUE50Ay2bN6elv0Ast4vhAyldLtCgIWHkBJf6BmsnVDxxnTlo+mCnMFk25FpTMq5CLIHNmOB8IojFej0svKX0yzGMsUi2ulUR3jzaULHmfaxMei+bIPegGpuBegB/jSupNWuEplMbBNfTrZdjtiNu/UoRAeG8nu6/S6lSQcRykBrng3WX7/CZ7mndtP7GEbmuqyHiQcGFkJxzljhMELuJV7pJNs5Jsv8aSF/FYOFRRdpMuSpfMT8F5ekR35g1vQfgRp/JdJBq7PqMD9xLzHGxoyfFwLB9TN7mgydRr8/PC1zqjn8w/WHzBUpCoAboZ04qynyghSm+UKlFzYgPVwHB3lPFR5SBiH40d9EIYpwpgk+zQdbZqHoqhqNQfA9+kCJWP7uKT4rsAjOxh9dFJYjtxhEc9jZ4X5Uz3BZ/cvnnhG2EgL8IvJJ15b8Jl2UnZC02kiiwGk5YvZyyqRHhnETv/6HVS/U0iQ73vQ5ikTgK9WxAKONHtgp0ooQ6jRzC7t+UVdLrbp3TgHYEF3/FzW0FSXyexhjYTwW7hsoSRB+ZtbDILNoTcd1WRuxug2R7juLyphh+BG20pHRBniBKo6AKTwuPEYi3iloCFVRjqCL23E0xwf6Qmul0KevjWOZa0v2RVIiWotZTTqn8283idwjEca3msKcR8Vof/W7/Sk=
  on:
    tags: true
    repo: okwolf/aes-gcm-promise
